rotation:
  cycle-minutes: 30
  start-cycle: "2025-07-27T00:00:00Z" # UTC ISO-8601 timestamp
  worlds:
    - id: "sahara"
      texture: "http://textures.minecraft.net/texture/abc123..."
      chat-name: "&cFirst Adventure World"
      gui-name: "&6Adventure World 1"
      lore:
        - "&6This is the first adventure world!"
        - "&6Add lore here"
      commands:
        - "say world 1"
    - id: "sahara"
      texture: "http://textures.minecraft.net/texture/def456..."
      chat-name: "&cSecond Adventure World"
      gui-name: "&6Adventure World 2"
      lore:
        - "&6This is the second adventure world!"
        - "&6Add lore here"
      commands:
        - "say world 2"
    - id: "sahara"
      texture: "http://textures.minecraft.net/texture/ghi789..."
      chat-name: "&cThird Adventure World"
      gui-name: "&6Adventure World 3"
      lore:
        - "&6This is the third adventure world!"
        - "&6Add lore here"
      commands:
        - "say world 3"

broadcast:
  warn-minutes: 5 # Broadcast this many minutes before rotation
  warn-message: "&e[Adventure] Map &a%current_map% &ecloses in &c%minutes% &eminutes!"
  new-map-message: "&a[Adventure] New map is now open: &b%new_map%!"

penalty:
  message: "&cThe map has collapsed! You are consumed by darkness..."
  sound: "ENTITY_WITHER_SPAWN" # Any Bukkit sound name

extraction:
  duration: 5 # seconds to stand in zone
  portal-restore-time: 3
  extraction-down-time: 5
  spawn:
    world: "spawn"
    x: 0
    y: 64
    z: 0
  message:
    title: "Extracting... %seconds%"
    start: "&aExtraction initiated! Hold still for %seconds% seconds..."
    success: "&aExtraction complete! Teleporting..."
    cancel: "&cYou left the extraction zone!"
  zones:
    adventure_world_1:
      - min: [0, 64, 0]
        max: [10, 70, 10]
        portal_min: [0, 0, 0]
        portal_max: [0, 0, 0]
        beacon_loc: []
        particle_loc: []
      - min: [20, 64, 20]
        max: [30, 70, 30]
    adventure_world_2:
      - min: [100, 64, 100]
        max: [110, 70, 110]
  alert-seconds: 3 # how many seconds before extraction to trigger alert
  alert:
      particles: true
      fireworks: true
      sound: ENTITY_ENDER_DRAGON_GROWL
      location:
        use-player: true # true = play at extracting player's position, false = fixed coords
        world: "adventure_world_1"
        x: 50
        y: 70
        z: 50

gui:
  title: "&6Adventure Menu"

  teleport:
    slot: 13
    name: "&aEnter: %current_world%"
    lore:
      - "&7Click to begin your adventure!"
      - "&7You are entering: %current_world%"

  info:
    slot: 22
    name: "&eCycle Info"
    lore:
      - "&7Closes in: %minutes_left% minutes"
      - "&7Next map: %next_world%"